import Database from "better-sqlite3";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const db = new Database(join(__dirname, "../data/altilio.db"));

// ── Extra filter options needed for Mozart tiles ─────────────────────────────
const insertOpt = db.prepare(
  "INSERT OR IGNORE INTO filter_options (category, value, label, metadata, sort_order) VALUES (?, ?, ?, ?, ?)"
);
const addOptions = db.transaction(() => {
  insertOpt.run("size",       "600×1200",          "600×1200 mm",         null, 10);
  insertOpt.run("collection", "syncstone_platinum", "SyncStone Platinum",  null, 10);
  insertOpt.run("collection", "syncstone_gold",     "SyncStone Gold",      null, 11);
  insertOpt.run("finish",     "plume_matt",          "Plume Matt",          null, 10);
  insertOpt.run("finish",     "punto",               "Punto",               null, 11);
  insertOpt.run("color",      "pink",  "Pink",  JSON.stringify({ hex: "#F4A7B9" }), 12);
  insertOpt.run("color",      "amber", "Amber", JSON.stringify({ hex: "#FFBF00" }), 13);
  insertOpt.run("color",      "blue_grey", "Blue Grey", JSON.stringify({ hex: "#78909C" }), 14);
});
addOptions();

// ── Tile data ─────────────────────────────────────────────────────────────────
const tiles = [
  // ── Marble Looks ────────────────────────────────────────────────────────────
  {
    name: "Nova",
    sku: "SS-NOV-PM",
    size: "600×1200",
    placement: "both",
    pattern: "marble",
    finish: "plume_matt",
    color: "white",
    price: 220,
    price_unit: "per_sqft",
    use_cases: "living_room, bathroom, lobby",
    collection: "syncstone_platinum",
    brand: "Mozart",
    image_path: "/tiles/nova.jpg",
    description: "Classic Calacatta-inspired white marble with flowing grey veins. A timeless choice for living rooms, bathrooms and hotel lobbies.",
  },
  {
    name: "Nova Liner",
    sku: "SS-NVL-PM",
    size: "600×1200",
    placement: "wall",
    pattern: "marble",
    finish: "plume_matt",
    color: "white",
    price: 235,
    price_unit: "per_sqft",
    use_cases: "bathroom, lobby",
    collection: "syncstone_platinum",
    brand: "Mozart",
    image_path: "/tiles/nova-liner.jpg",
    description: "Nova's striking white marble base with a fine liner embossing. Adds subtle texture and dimension to feature walls and bathroom accents.",
  },
  {
    name: "Flame",
    sku: "SS-FLM-PM",
    size: "600×1200",
    placement: "both",
    pattern: "marble",
    finish: "plume_matt",
    color: "white",
    price: 245,
    price_unit: "per_sqft",
    use_cases: "bathroom, living_room, lobby",
    collection: "syncstone_platinum",
    brand: "Mozart",
    image_path: "/tiles/flame.jpg",
    description: "Dramatic white marble with bold gold and rust veining reminiscent of Calacatta Oro. A statement tile for luxury interiors.",
  },
  {
    name: "Harmony",
    sku: "SS-HRM-PM",
    size: "600×1200",
    placement: "both",
    pattern: "marble",
    finish: "plume_matt",
    color: "white",
    price: 230,
    price_unit: "per_sqft",
    use_cases: "living_room, bathroom, commercial",
    collection: "syncstone_platinum",
    brand: "Mozart",
    image_path: "/tiles/harmony.jpg",
    description: "Elegant white marble infused with warm copper-orange veins. Brings warmth and opulence to dining areas and corporate offices.",
  },
  {
    name: "Melody Sand",
    sku: "SS-MLS-PM",
    size: "600×1200",
    placement: "both",
    pattern: "marble",
    finish: "plume_matt",
    color: "beige",
    price: 210,
    price_unit: "per_sqft",
    use_cases: "bedroom, bathroom, living_room",
    collection: "syncstone_platinum",
    brand: "Mozart",
    image_path: "/tiles/melody-sand.jpg",
    description: "Soft cream-beige marble with delicate veining for a serene, spa-like atmosphere. Ideal for bedrooms and luxury bathrooms.",
  },
  {
    name: "Melody Gris",
    sku: "SS-MLG-PM",
    size: "600×1200",
    placement: "both",
    pattern: "marble",
    finish: "plume_matt",
    color: "grey",
    price: 210,
    price_unit: "per_sqft",
    use_cases: "living_room, bathroom, commercial",
    collection: "syncstone_platinum",
    brand: "Mozart",
    image_path: "/tiles/melody-gris.jpg",
    description: "Cool grey marble with flowing white veins. Sophisticated and versatile for contemporary residential and commercial spaces.",
  },
  {
    name: "Melody Mint",
    sku: "SS-MLM-PM",
    size: "600×1200",
    placement: "both",
    pattern: "marble",
    finish: "plume_matt",
    color: "white",
    price: 215,
    price_unit: "per_sqft",
    use_cases: "bathroom, living_room, bedroom",
    collection: "syncstone_platinum",
    brand: "Mozart",
    image_path: "/tiles/melody-mint.jpg",
    description: "White marble with subtle cool-mint undertones and fine diagonal veining. A refined choice for bathrooms and feature walls.",
  },
  {
    name: "Ocean Wave",
    sku: "SS-OCW-PM",
    size: "600×1200",
    placement: "both",
    pattern: "marble",
    finish: "plume_matt",
    color: "blue_grey",
    price: 265,
    price_unit: "per_sqft",
    use_cases: "living_room, lobby, bathroom",
    collection: "syncstone_platinum",
    brand: "Mozart",
    image_path: "/tiles/ocean-wave.jpg",
    description: "Spectacular blue-grey marble with cascading wave-like veining. Creates an awe-inspiring focal point in living rooms and hotel lobbies.",
  },
  {
    name: "Picasso",
    sku: "SS-PCS-PM",
    size: "600×1200",
    placement: "both",
    pattern: "marble",
    finish: "plume_matt",
    color: "beige",
    price: 255,
    price_unit: "per_sqft",
    use_cases: "bathroom, living_room, lobby",
    collection: "syncstone_platinum",
    brand: "Mozart",
    image_path: "/tiles/picasso.jpg",
    description: "Artistic onyx-like tile with cream and amber tones merging in abstract cloud patterns. A truly unique surface for luxury spaces.",
  },
  // ── Stone & Concrete Looks ──────────────────────────────────────────────────
  {
    name: "Morning Glory",
    sku: "SS-MGR-PM",
    size: "600×1200",
    placement: "both",
    pattern: "stone",
    finish: "plume_matt",
    color: "cream",
    price: 175,
    price_unit: "per_sqft",
    use_cases: "living_room, bedroom, commercial",
    collection: "syncstone_platinum",
    brand: "Mozart",
    image_path: "/tiles/morning-glory.jpg",
    description: "Soft cream-ivory stone look with barely-there cloud texture. A clean, versatile backdrop that complements any interior style.",
  },
  {
    name: "Midnight Black",
    sku: "SS-MDB-PM",
    size: "600×1200",
    placement: "both",
    pattern: "plain",
    finish: "plume_matt",
    color: "black",
    price: 195,
    price_unit: "per_sqft",
    use_cases: "bathroom, commercial, living_room",
    collection: "syncstone_platinum",
    brand: "Mozart",
    image_path: "/tiles/midnight-black.jpg",
    description: "Deep charcoal-black fullbody tile with a matte finish. Striking in minimalist and dramatic interiors; hides wear exceptionally well.",
  },
  {
    name: "Dynamic Sand",
    sku: "SS-DYS-PM",
    size: "600×1200",
    placement: "both",
    pattern: "stone",
    finish: "plume_matt",
    color: "beige",
    price: 185,
    price_unit: "per_sqft",
    use_cases: "living_room, bedroom, commercial",
    collection: "syncstone_platinum",
    brand: "Mozart",
    image_path: "/tiles/dynamic-sand.jpg",
    description: "Warm sandy-beige with subtle linear veining. Brings a natural, earthy energy to open-plan living areas and hallways.",
  },
  {
    name: "Luna Franch",
    sku: "SS-LNF-PM",
    size: "600×1200",
    placement: "both",
    pattern: "stone",
    finish: "plume_matt",
    color: "pink",
    price: 195,
    price_unit: "per_sqft",
    use_cases: "bedroom, bathroom",
    collection: "syncstone_platinum",
    brand: "Mozart",
    image_path: "/tiles/luna-franch.jpg",
    description: "Delicate blush-rose stone look with a soft matte surface. Creates a warm, feminine atmosphere in bedrooms and en-suite bathrooms.",
  },
  {
    name: "Luna Amber",
    sku: "SS-LNA-PM",
    size: "600×1200",
    placement: "both",
    pattern: "stone",
    finish: "plume_matt",
    color: "amber",
    price: 195,
    price_unit: "per_sqft",
    use_cases: "bathroom, bedroom, lobby",
    collection: "syncstone_platinum",
    brand: "Mozart",
    image_path: "/tiles/luna-amber.jpg",
    description: "Warm amber-honey stone with gentle mottling. Evokes the richness of natural limestone in a durable fullbody format.",
  },
  {
    name: "Porto Bello",
    sku: "SS-PTB-PM",
    size: "600×1200",
    placement: "both",
    pattern: "concrete",
    finish: "plume_matt",
    color: "grey",
    price: 180,
    price_unit: "per_sqft",
    use_cases: "commercial, living_room, outdoor",
    collection: "syncstone_platinum",
    brand: "Mozart",
    image_path: "/tiles/porto-bello.jpg",
    description: "Weathered industrial concrete look with subtle variation and raw texture. Perfect for modern urban interiors and facade cladding.",
  },
  {
    name: "Rock Sand",
    sku: "SS-RKS-PM",
    size: "600×1200",
    placement: "both",
    pattern: "stone",
    finish: "plume_matt",
    color: "terracotta",
    price: 185,
    price_unit: "per_sqft",
    use_cases: "living_room, outdoor, commercial",
    collection: "syncstone_platinum",
    brand: "Mozart",
    image_path: "/tiles/rock-sand.jpg",
    description: "Warm terracotta-toned stone with organic texture. Adds earthiness and character to living walls, feature walls and outdoor areas.",
  },
  {
    name: "Rock Gris",
    sku: "SS-RKG-PM",
    size: "600×1200",
    placement: "both",
    pattern: "stone",
    finish: "plume_matt",
    color: "grey",
    price: 185,
    price_unit: "per_sqft",
    use_cases: "living_room, outdoor, commercial",
    collection: "syncstone_platinum",
    brand: "Mozart",
    image_path: "/tiles/rock-gris.jpg",
    description: "Cool grey stone with a naturally worn surface texture. Versatile for both indoor and outdoor applications where strength matters.",
  },
  {
    name: "Grafito",
    sku: "SS-GRF-PM",
    size: "600×1200",
    placement: "both",
    pattern: "stone",
    finish: "plume_matt",
    color: "beige",
    price: 180,
    price_unit: "per_sqft",
    use_cases: "living_room, commercial, outdoor",
    collection: "syncstone_platinum",
    brand: "Mozart",
    image_path: "/tiles/grafito.jpg",
    description: "Warm taupe-beige stone with a finely textured surface. A balanced, neutral tile that adapts easily to any colour scheme.",
  },
  {
    name: "Bella Clay",
    sku: "SS-BLC-PM",
    size: "600×1200",
    placement: "both",
    pattern: "stone",
    finish: "plume_matt",
    color: "beige",
    price: 190,
    price_unit: "per_sqft",
    use_cases: "living_room, commercial, outdoor",
    collection: "syncstone_platinum",
    brand: "Mozart",
    image_path: "/tiles/bella-clay.jpg",
    description: "Aged clay-stone surface with warm buff tones and natural imperfections. Brings character to floors and textured feature walls.",
  },
  {
    name: "Bella Sand",
    sku: "SS-BLS-PM",
    size: "600×1200",
    placement: "both",
    pattern: "stone",
    finish: "plume_matt",
    color: "terracotta",
    price: 190,
    price_unit: "per_sqft",
    use_cases: "outdoor, commercial, living_room",
    collection: "syncstone_platinum",
    brand: "Mozart",
    image_path: "/tiles/bella-sand.jpg",
    description: "Rustic terracotta-and-sand stone with a worn, antiqued finish. Ideal for courtyards, restaurants and boutique retail.",
  },
  {
    name: "Bella Gris",
    sku: "SS-BLG-PM",
    size: "600×1200",
    placement: "both",
    pattern: "concrete",
    finish: "plume_matt",
    color: "grey",
    price: 190,
    price_unit: "per_sqft",
    use_cases: "commercial, living_room, bathroom",
    collection: "syncstone_platinum",
    brand: "Mozart",
    image_path: "/tiles/bella-gris.jpg",
    description: "Clean mid-grey concrete look with subtle aggregate texture. A go-to for modern commercial and minimalist residential projects.",
  },
  {
    name: "Bella Grigio",
    sku: "SS-BLR-PM",
    size: "600×1200",
    placement: "both",
    pattern: "concrete",
    finish: "plume_matt",
    color: "grey",
    price: 195,
    price_unit: "per_sqft",
    use_cases: "commercial, living_room, bathroom",
    collection: "syncstone_platinum",
    brand: "Mozart",
    image_path: "/tiles/bella-grigio.jpg",
    description: "Textured grey with a lightly embossed mosaic-micro pattern. Adds tactile depth while maintaining the clean look of concrete.",
  },
  {
    name: "Grani Sand",
    sku: "SS-GNS-PM",
    size: "600×1200",
    placement: "both",
    pattern: "stone",
    finish: "plume_matt",
    color: "beige",
    price: 200,
    price_unit: "per_sqft",
    use_cases: "outdoor, commercial, living_room",
    collection: "syncstone_platinum",
    brand: "Mozart",
    image_path: "/tiles/grani-sand.jpg",
    description: "Speckled granite-like surface in warm sand tones. Fullbody construction ensures consistent look even at cut edges.",
  },
  {
    name: "Brixstone",
    sku: "SS-BRX-PM",
    size: "600×1200",
    placement: "both",
    pattern: "stone",
    finish: "plume_matt",
    color: "beige",
    price: 205,
    price_unit: "per_sqft",
    use_cases: "outdoor, commercial, living_room",
    collection: "syncstone_platinum",
    brand: "Mozart",
    image_path: "/tiles/brixstone.jpg",
    description: "Multi-tonal stacked-brick stone pattern with an aged, quarried feel. Outstanding for exterior facades, accent walls and alfresco dining.",
  },
  {
    name: "Corten Stone",
    sku: "SS-CTS-PU",
    size: "600×1200",
    placement: "both",
    pattern: "abstract",
    finish: "punto",
    color: "brown",
    price: 250,
    price_unit: "per_sqft",
    use_cases: "living_room, lobby, outdoor",
    collection: "syncstone_platinum",
    brand: "Mozart",
    image_path: "/tiles/corten-stone.jpg",
    description: "Inspired by weathered Corten steel — a diagonal split of warm rusty-orange and cool grey. A bold, artistic statement surface.",
  },
  // ── Travertino Series ───────────────────────────────────────────────────────
  {
    name: "Travertino Natural",
    sku: "SS-TVN-PM",
    size: "600×1200",
    placement: "both",
    pattern: "stone",
    finish: "plume_matt",
    color: "beige",
    price: 220,
    price_unit: "per_sqft",
    use_cases: "living_room, lobby, commercial",
    collection: "syncstone_platinum",
    brand: "Mozart",
    image_path: "/tiles/travertino-natural.jpg",
    description: "Authentic travertine look in warm ivory-beige with delicate horizontal striations. Timeless elegance for premium residential and hotel projects.",
  },
  {
    name: "Travertino Gris",
    sku: "SS-TVG-PM",
    size: "600×1200",
    placement: "both",
    pattern: "stone",
    finish: "plume_matt",
    color: "grey",
    price: 220,
    price_unit: "per_sqft",
    use_cases: "living_room, lobby, commercial",
    collection: "syncstone_platinum",
    brand: "Mozart",
    image_path: "/tiles/travertino-gris.jpg",
    description: "Silver-grey travertine with fine horizontal grain. Brings an understated luxury to open-plan kitchens and corporate lobbies.",
  },
  {
    name: "Travertino Mint Dark",
    sku: "SS-TMD-PM",
    size: "600×1200",
    placement: "both",
    pattern: "stone",
    finish: "plume_matt",
    color: "beige",
    price: 225,
    price_unit: "per_sqft",
    use_cases: "living_room, commercial, lobby",
    collection: "syncstone_platinum",
    brand: "Mozart",
    image_path: "/tiles/travertino-mint-dark.jpg",
    description: "Rich warm-tan travertine with pronounced linear grain and dark accents. Creates depth and drama in large open spaces.",
  },
  {
    name: "Travertino Sand Light",
    sku: "SS-TSL-PM",
    size: "600×1200",
    placement: "both",
    pattern: "stone",
    finish: "plume_matt",
    color: "cream",
    price: 215,
    price_unit: "per_sqft",
    use_cases: "bedroom, living_room, lobby",
    collection: "syncstone_platinum",
    brand: "Mozart",
    image_path: "/tiles/travertino-sand-light.jpg",
    description: "Pale cream travertine with fine wood-grain striations. Soft and serene — ideal for bedrooms, spa bathrooms and boutique hotel rooms.",
  },
  {
    name: "Travertino Sand Dark",
    sku: "SS-TSD-PM",
    size: "600×1200",
    placement: "both",
    pattern: "stone",
    finish: "plume_matt",
    color: "brown",
    price: 215,
    price_unit: "per_sqft",
    use_cases: "living_room, commercial, lobby",
    collection: "syncstone_platinum",
    brand: "Mozart",
    image_path: "/tiles/travertino-sand-dark.jpg",
    description: "Warm walnut-toned travertine with deep horizontal grain. A grounding, sophisticated choice for feature floors and wall panels.",
  },
];

// ── Insert tiles ──────────────────────────────────────────────────────────────
// Clear existing tiles first for a clean seed
db.exec("DELETE FROM tiles");

const stmt = db.prepare(`
  INSERT INTO tiles
    (name, sku, size, placement, pattern, finish, color, price, price_unit,
     use_cases, collection, brand, image_path, description)
  VALUES
    (@name, @sku, @size, @placement, @pattern, @finish, @color, @price, @price_unit,
     @use_cases, @collection, @brand, @image_path, @description)
`);

const insertAll = db.transaction(() => {
  for (const tile of tiles) stmt.run(tile);
});

insertAll();
console.log(`✓ Seeded ${tiles.length} Mozart SyncStone tiles.`);
db.close();
