import Database from "better-sqlite3";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const db = new Database(join(__dirname, "../data/altilio.db"));

const tiles = [
  {
    name: "Carrara White 600",
    sku: "CW-600-P",
    size: "600×600",
    placement: "wall",
    pattern: "marble",
    finish: "polished",
    color: "white",
    price: 185,
    price_unit: "per_sqft",
    use_cases: "bathroom, kitchen",
    collection: "luxury_marble",
    brand: "Somany",
    image_path: null,
    description: "Classic Italian-inspired Carrara marble with subtle grey veining. Ideal for premium bathrooms and feature walls.",
  },
  {
    name: "Grigio Slate 800",
    sku: "GS-800-T",
    size: "800×800",
    placement: "floor",
    pattern: "stone",
    finish: "textured",
    color: "grey",
    price: 210,
    price_unit: "per_sqft",
    use_cases: "living_room, outdoor",
    collection: "heritage_stone",
    brand: "RAK Ceramics",
    image_path: null,
    description: "Large-format grey slate texture with anti-slip surface, perfect for living spaces and outdoor decks.",
  },
  {
    name: "Teak Wood Plank",
    sku: "TW-1200-M",
    size: "1200×200",
    placement: "both",
    pattern: "wood",
    finish: "matte",
    color: "brown",
    price: 155,
    price_unit: "per_sqft",
    use_cases: "bedroom, living_room",
    collection: "nature_wood",
    brand: "Johnson Tiles",
    image_path: null,
    description: "Realistic teak wood plank design with micro-embossed grain texture. Warm and inviting for any floor or feature wall.",
  },
  {
    name: "Nero Marquina",
    sku: "NM-600-G",
    size: "600×600",
    placement: "wall",
    pattern: "marble",
    finish: "glossy",
    color: "black",
    price: 320,
    price_unit: "per_sqft",
    use_cases: "bathroom",
    collection: "luxury_marble",
    brand: "Somany",
    image_path: null,
    description: "Dramatic black marble with gold veining. Statement tile for luxury bathrooms and powder rooms.",
  },
  {
    name: "Urban Cement 600",
    sku: "UC-600-M",
    size: "600×600",
    placement: "floor",
    pattern: "concrete",
    finish: "matte",
    color: "grey",
    price: 95,
    price_unit: "per_sqft",
    use_cases: "commercial, living_room",
    collection: "urban_concrete",
    brand: "Nitco",
    image_path: null,
    description: "Minimalist cement-look tile with subtle texture variation. Popular in modern industrial and Scandinavian interiors.",
  },
  {
    name: "Arabesque Gold",
    sku: "AG-300-G",
    size: "300×300",
    placement: "wall",
    pattern: "geometric",
    finish: "glossy",
    color: "gold",
    price: 275,
    price_unit: "per_sqft",
    use_cases: "bathroom, kitchen",
    collection: "designer_series",
    brand: "RAK Ceramics",
    image_path: null,
    description: "Intricate Moorish arabesque pattern with metallic gold glaze. Ideal as a feature wall or backsplash accent.",
  },
  {
    name: "Snow White Plain",
    sku: "SW-600-M",
    size: "600×600",
    placement: "both",
    pattern: "plain",
    finish: "matte",
    color: "white",
    price: 75,
    price_unit: "per_sqft",
    use_cases: "bathroom, kitchen, living_room",
    collection: "classic_white",
    brand: "Asian Granito",
    image_path: null,
    description: "Versatile full-body white tile. Timeless, easy to maintain, works with any décor style.",
  },
  {
    name: "Terracotta Rustic",
    sku: "TC-400-R",
    size: "400×400",
    placement: "floor",
    pattern: "plain",
    finish: "rustic",
    color: "terracotta",
    price: 120,
    price_unit: "per_sqft",
    use_cases: "outdoor, balcony",
    collection: "heritage_stone",
    brand: "Nitco",
    image_path: null,
    description: "Handcrafted terracotta-look tile with natural colour variation and weathered finish. Great for courtyards and balconies.",
  },
  {
    name: "Bianco Calacatta XL",
    sku: "BC-1200-P",
    size: "1200×600",
    placement: "wall",
    pattern: "marble",
    finish: "polished",
    color: "white",
    price: 395,
    price_unit: "per_sqft",
    use_cases: "bathroom, lobby",
    collection: "luxury_marble",
    brand: "Somany",
    image_path: null,
    description: "Ultra-premium Calacatta marble replica with bold gold veining. Creates stunning feature walls in bathrooms and hotel lobbies.",
  },
  {
    name: "Hex Mosaica Blue",
    sku: "HM-300-G",
    size: "300×300",
    placement: "wall",
    pattern: "mosaic",
    finish: "glossy",
    color: "blue",
    price: 240,
    price_unit: "per_sqft",
    use_cases: "bathroom, kitchen",
    collection: "designer_series",
    brand: "Johnson Tiles",
    image_path: null,
    description: "Hexagonal mosaic pattern in ocean blue gradient glaze. Striking backsplash or shower accent tile.",
  },
  {
    name: "Charcoal Lappato 800",
    sku: "CL-800-L",
    size: "800×800",
    placement: "floor",
    pattern: "plain",
    finish: "lappato",
    color: "charcoal",
    price: 175,
    price_unit: "per_sqft",
    use_cases: "living_room, commercial",
    collection: "urban_concrete",
    brand: "Asian Granito",
    image_path: null,
    description: "Large-format charcoal tile with semi-polished lappato finish for a subtle sheen without showing scratches.",
  },
  {
    name: "Oak Herringbone Plank",
    sku: "OH-600-M",
    size: "600×100",
    placement: "floor",
    pattern: "wood",
    finish: "matte",
    color: "beige",
    price: 195,
    price_unit: "per_sqft",
    use_cases: "bedroom, living_room",
    collection: "nature_wood",
    brand: "Johnson Tiles",
    image_path: null,
    description: "Slim plank tiles designed to be laid in herringbone pattern. Captures the warmth of real oak flooring.",
  },
  {
    name: "Sage Green Zellige",
    sku: "SG-100-G",
    size: "100×100",
    placement: "wall",
    pattern: "zellige",
    finish: "glossy",
    color: "green",
    price: 310,
    price_unit: "per_sqft",
    use_cases: "kitchen, bathroom",
    collection: "designer_series",
    brand: "RAK Ceramics",
    image_path: null,
    description: "Handmade zellige-inspired tiles with natural glaze variation in sage green. Creates a rich, artisanal wall surface.",
  },
  {
    name: "Crema Beige 600",
    sku: "CB-600-S",
    size: "600×600",
    placement: "both",
    pattern: "stone",
    finish: "satin",
    color: "beige",
    price: 130,
    price_unit: "per_sqft",
    use_cases: "living_room, bedroom, bathroom",
    collection: "heritage_stone",
    brand: "Asian Granito",
    image_path: null,
    description: "Warm beige stone-look tile with satin finish. Versatile and neutral — pairs well with any interior palette.",
  },
  {
    name: "Terrazzo Milano",
    sku: "TM-600-M",
    size: "600×600",
    placement: "floor",
    pattern: "terrazzo",
    finish: "polished",
    color: "cream",
    price: 225,
    price_unit: "per_sqft",
    use_cases: "lobby, living_room, commercial",
    collection: "designer_series",
    brand: "Somany",
    image_path: null,
    description: "Modern terrazzo with colourful aggregate chips set in a cream base. Brings a retro-contemporary vibe to any space.",
  },
];

const stmt = db.prepare(`
  INSERT OR IGNORE INTO tiles (name, sku, size, placement, pattern, finish, color, price, price_unit, use_cases, collection, brand, image_path, description)
  VALUES (@name, @sku, @size, @placement, @pattern, @finish, @color, @price, @price_unit, @use_cases, @collection, @brand, @image_path, @description)
`);

const insertAll = db.transaction(() => {
  for (const tile of tiles) {
    stmt.run(tile);
  }
});

insertAll();
console.log(`Inserted ${tiles.length} dummy tiles.`);
db.close();
