import Database from "better-sqlite3";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const db = new Database(join(__dirname, "../data/altilio.db"));

// ── Extra filter options needed for Mozart tiles ─────────────────────────────
const insertOpt = db.prepare(
  "INSERT OR IGNORE INTO filter_options (category, value, label, metadata, sort_order) VALUES (?, ?, ?, ?, ?)"
);
const addOptions = db.transaction(() => {
  insertOpt.run("size",       "600×1200",          "600×1200 mm",         null, 10);
  // Collections
  insertOpt.run("collection", "syncstone_platinum", "SyncStone Platinum",  null, 10);
  insertOpt.run("collection", "syncstone_gold",     "SyncStone Gold",      null, 11);
  insertOpt.run("collection", "frame_collection",   "Frame Collection",    null, 12);
  insertOpt.run("collection", "wainscot_series",    "Wainscot Series",     null, 13);
  // Finishes
  insertOpt.run("finish",     "plume_matt",          "Plume Matt",          null, 10);
  insertOpt.run("finish",     "punto",               "Punto",               null, 11);
  insertOpt.run("finish",     "matt",                "Matt",                null, 12);
  // Colors
  insertOpt.run("color",      "pink",      "Pink",       JSON.stringify({ hex: "#F4A7B9" }), 12);
  insertOpt.run("color",      "amber",     "Amber",      JSON.stringify({ hex: "#FFBF00" }), 13);
  insertOpt.run("color",      "blue_grey", "Blue Grey",  JSON.stringify({ hex: "#78909C" }), 14);
  insertOpt.run("color",      "aqua",      "Aqua",       JSON.stringify({ hex: "#B2DFD8" }), 15);
  insertOpt.run("color",      "sage",      "Sage",       JSON.stringify({ hex: "#9CAF88" }), 16);
  insertOpt.run("color",      "green",     "Green",      JSON.stringify({ hex: "#4A7C59" }), 17);
  insertOpt.run("color",      "navy",      "Navy",       JSON.stringify({ hex: "#4A5C7A" }), 18);
  insertOpt.run("color",      "taupe",     "Taupe",      JSON.stringify({ hex: "#9E8E7E" }), 19);
  insertOpt.run("color",      "salmon",    "Salmon",     JSON.stringify({ hex: "#E8846A" }), 20);
  insertOpt.run("color",      "dark_grey", "Dark Grey",  JSON.stringify({ hex: "#5A5A5A" }), 21);
  // Patterns
  insertOpt.run("pattern",    "frame",     "Frame",      null, 10);
  insertOpt.run("pattern",    "wainscot",  "Wainscot",   null, 11);
  insertOpt.run("pattern",    "floral",    "Floral",     null, 12);
});
addOptions();

// ── Tile data ─────────────────────────────────────────────────────────────────
const tiles = [
  // ── Marble Looks ────────────────────────────────────────────────────────────
  {
    name: "Nova",
    sku: "SS-NOV-PM",
    size: "600×1200",
    placement: "both",
    pattern: "marble",
    finish: "plume_matt",
    color: "white",
    price: 220,
    price_unit: "per_sqft",
    use_cases: "living_room, bathroom, lobby",
    collection: "syncstone_platinum",
    brand: "Mozart",
    image_path: "/tiles/nova.jpg",
    description: "Classic Calacatta-inspired white marble with flowing grey veins. A timeless choice for living rooms, bathrooms and hotel lobbies.",
  },
  {
    name: "Nova Liner",
    sku: "SS-NVL-PM",
    size: "600×1200",
    placement: "wall",
    pattern: "marble",
    finish: "plume_matt",
    color: "white",
    price: 235,
    price_unit: "per_sqft",
    use_cases: "bathroom, lobby",
    collection: "syncstone_platinum",
    brand: "Mozart",
    image_path: "/tiles/nova-liner.jpg",
    description: "Nova's striking white marble base with a fine liner embossing. Adds subtle texture and dimension to feature walls and bathroom accents.",
  },
  {
    name: "Flame",
    sku: "SS-FLM-PM",
    size: "600×1200",
    placement: "both",
    pattern: "marble",
    finish: "plume_matt",
    color: "white",
    price: 245,
    price_unit: "per_sqft",
    use_cases: "bathroom, living_room, lobby",
    collection: "syncstone_platinum",
    brand: "Mozart",
    image_path: null,
    description: "Dramatic white marble with bold gold and rust veining reminiscent of Calacatta Oro. A statement tile for luxury interiors.",
  },
  {
    name: "Harmony",
    sku: "SS-HRM-PM",
    size: "600×1200",
    placement: "both",
    pattern: "marble",
    finish: "plume_matt",
    color: "white",
    price: 230,
    price_unit: "per_sqft",
    use_cases: "living_room, bathroom, commercial",
    collection: "syncstone_platinum",
    brand: "Mozart",
    image_path: "/tiles/harmony.jpg",
    description: "Elegant white marble infused with warm copper-orange veins. Brings warmth and opulence to dining areas and corporate offices.",
  },
  {
    name: "Melody Sand",
    sku: "SS-MLS-PM",
    size: "600×1200",
    placement: "both",
    pattern: "marble",
    finish: "plume_matt",
    color: "beige",
    price: 210,
    price_unit: "per_sqft",
    use_cases: "bedroom, bathroom, living_room",
    collection: "syncstone_platinum",
    brand: "Mozart",
    image_path: null,
    description: "Soft cream-beige marble with delicate veining for a serene, spa-like atmosphere. Ideal for bedrooms and luxury bathrooms.",
  },
  {
    name: "Melody Gris",
    sku: "SS-MLG-PM",
    size: "600×1200",
    placement: "both",
    pattern: "marble",
    finish: "plume_matt",
    color: "grey",
    price: 210,
    price_unit: "per_sqft",
    use_cases: "living_room, bathroom, commercial",
    collection: "syncstone_platinum",
    brand: "Mozart",
    image_path: null,
    description: "Cool grey marble with flowing white veins. Sophisticated and versatile for contemporary residential and commercial spaces.",
  },
  {
    name: "Melody Mint",
    sku: "SS-MLM-PM",
    size: "600×1200",
    placement: "both",
    pattern: "marble",
    finish: "plume_matt",
    color: "white",
    price: 215,
    price_unit: "per_sqft",
    use_cases: "bathroom, living_room, bedroom",
    collection: "syncstone_platinum",
    brand: "Mozart",
    image_path: null,
    description: "White marble with subtle cool-mint undertones and fine diagonal veining. A refined choice for bathrooms and feature walls.",
  },
  {
    name: "Ocean Wave",
    sku: "SS-OCW-PM",
    size: "600×1200",
    placement: "both",
    pattern: "marble",
    finish: "plume_matt",
    color: "blue_grey",
    price: 265,
    price_unit: "per_sqft",
    use_cases: "living_room, lobby, bathroom",
    collection: "syncstone_platinum",
    brand: "Mozart",
    image_path: "/tiles/ocean-wave.jpg",
    description: "Spectacular blue-grey marble with cascading wave-like veining. Creates an awe-inspiring focal point in living rooms and hotel lobbies.",
  },
  {
    name: "Picasso",
    sku: "SS-PCS-PM",
    size: "600×1200",
    placement: "both",
    pattern: "marble",
    finish: "plume_matt",
    color: "beige",
    price: 255,
    price_unit: "per_sqft",
    use_cases: "bathroom, living_room, lobby",
    collection: "syncstone_platinum",
    brand: "Mozart",
    image_path: "/tiles/picasso.jpg",
    description: "Artistic onyx-like tile with cream and amber tones merging in abstract cloud patterns. A truly unique surface for luxury spaces.",
  },
  // ── Stone & Concrete Looks ──────────────────────────────────────────────────
  {
    name: "Morning Glory",
    sku: "SS-MGR-PM",
    size: "600×1200",
    placement: "both",
    pattern: "stone",
    finish: "plume_matt",
    color: "cream",
    price: 175,
    price_unit: "per_sqft",
    use_cases: "living_room, bedroom, commercial",
    collection: "syncstone_platinum",
    brand: "Mozart",
    image_path: null,
    description: "Soft cream-ivory stone look with barely-there cloud texture. A clean, versatile backdrop that complements any interior style.",
  },
  {
    name: "Midnight Black",
    sku: "SS-MDB-PM",
    size: "600×1200",
    placement: "both",
    pattern: "plain",
    finish: "plume_matt",
    color: "black",
    price: 195,
    price_unit: "per_sqft",
    use_cases: "bathroom, commercial, living_room",
    collection: "syncstone_platinum",
    brand: "Mozart",
    image_path: null,
    description: "Deep charcoal-black fullbody tile with a matte finish. Striking in minimalist and dramatic interiors; hides wear exceptionally well.",
  },
  {
    name: "Dynamic Sand",
    sku: "SS-DYS-PM",
    size: "600×1200",
    placement: "both",
    pattern: "stone",
    finish: "plume_matt",
    color: "beige",
    price: 185,
    price_unit: "per_sqft",
    use_cases: "living_room, bedroom, commercial",
    collection: "syncstone_platinum",
    brand: "Mozart",
    image_path: null,
    description: "Warm sandy-beige with subtle linear veining. Brings a natural, earthy energy to open-plan living areas and hallways.",
  },
  {
    name: "Luna Franch",
    sku: "SS-LNF-PM",
    size: "600×1200",
    placement: "both",
    pattern: "stone",
    finish: "plume_matt",
    color: "pink",
    price: 195,
    price_unit: "per_sqft",
    use_cases: "bedroom, bathroom",
    collection: "syncstone_platinum",
    brand: "Mozart",
    image_path: null,
    description: "Delicate blush-rose stone look with a soft matte surface. Creates a warm, feminine atmosphere in bedrooms and en-suite bathrooms.",
  },
  {
    name: "Luna Amber",
    sku: "SS-LNA-PM",
    size: "600×1200",
    placement: "both",
    pattern: "stone",
    finish: "plume_matt",
    color: "amber",
    price: 195,
    price_unit: "per_sqft",
    use_cases: "bathroom, bedroom, lobby",
    collection: "syncstone_platinum",
    brand: "Mozart",
    image_path: "/tiles/luna-amber.jpg",
    description: "Warm amber-honey stone with gentle mottling. Evokes the richness of natural limestone in a durable fullbody format.",
  },
  {
    name: "Porto Bello",
    sku: "SS-PTB-PM",
    size: "600×1200",
    placement: "both",
    pattern: "concrete",
    finish: "plume_matt",
    color: "grey",
    price: 180,
    price_unit: "per_sqft",
    use_cases: "commercial, living_room, outdoor",
    collection: "syncstone_platinum",
    brand: "Mozart",
    image_path: "/tiles/porto-bello.jpg",
    description: "Weathered industrial concrete look with subtle variation and raw texture. Perfect for modern urban interiors and facade cladding.",
  },
  {
    name: "Rock Sand",
    sku: "SS-RKS-PM",
    size: "600×1200",
    placement: "both",
    pattern: "stone",
    finish: "plume_matt",
    color: "terracotta",
    price: 185,
    price_unit: "per_sqft",
    use_cases: "living_room, outdoor, commercial",
    collection: "syncstone_platinum",
    brand: "Mozart",
    image_path: "/tiles/rock-sand.jpg",
    description: "Warm terracotta-toned stone with organic texture. Adds earthiness and character to living walls, feature walls and outdoor areas.",
  },
  {
    name: "Rock Gris",
    sku: "SS-RKG-PM",
    size: "600×1200",
    placement: "both",
    pattern: "stone",
    finish: "plume_matt",
    color: "grey",
    price: 185,
    price_unit: "per_sqft",
    use_cases: "living_room, outdoor, commercial",
    collection: "syncstone_platinum",
    brand: "Mozart",
    image_path: null,
    description: "Cool grey stone with a naturally worn surface texture. Versatile for both indoor and outdoor applications where strength matters.",
  },
  {
    name: "Grafito",
    sku: "SS-GRF-PM",
    size: "600×1200",
    placement: "both",
    pattern: "stone",
    finish: "plume_matt",
    color: "beige",
    price: 180,
    price_unit: "per_sqft",
    use_cases: "living_room, commercial, outdoor",
    collection: "syncstone_platinum",
    brand: "Mozart",
    image_path: null,
    description: "Warm taupe-beige stone with a finely textured surface. A balanced, neutral tile that adapts easily to any colour scheme.",
  },
  {
    name: "Bella Clay",
    sku: "SS-BLC-PM",
    size: "600×1200",
    placement: "both",
    pattern: "stone",
    finish: "plume_matt",
    color: "beige",
    price: 190,
    price_unit: "per_sqft",
    use_cases: "living_room, commercial, outdoor",
    collection: "syncstone_platinum",
    brand: "Mozart",
    image_path: "/tiles/bella-clay.jpg",
    description: "Aged clay-stone surface with warm buff tones and natural imperfections. Brings character to floors and textured feature walls.",
  },
  {
    name: "Bella Sand",
    sku: "SS-BLS-PM",
    size: "600×1200",
    placement: "both",
    pattern: "stone",
    finish: "plume_matt",
    color: "terracotta",
    price: 190,
    price_unit: "per_sqft",
    use_cases: "outdoor, commercial, living_room",
    collection: "syncstone_platinum",
    brand: "Mozart",
    image_path: null,
    description: "Rustic terracotta-and-sand stone with a worn, antiqued finish. Ideal for courtyards, restaurants and boutique retail.",
  },
  {
    name: "Bella Gris",
    sku: "SS-BLG-PM",
    size: "600×1200",
    placement: "both",
    pattern: "concrete",
    finish: "plume_matt",
    color: "grey",
    price: 190,
    price_unit: "per_sqft",
    use_cases: "commercial, living_room, bathroom",
    collection: "syncstone_platinum",
    brand: "Mozart",
    image_path: "/tiles/bella-gris.jpg",
    description: "Clean mid-grey concrete look with subtle aggregate texture. A go-to for modern commercial and minimalist residential projects.",
  },
  {
    name: "Bella Grigio",
    sku: "SS-BLR-PM",
    size: "600×1200",
    placement: "both",
    pattern: "concrete",
    finish: "plume_matt",
    color: "grey",
    price: 195,
    price_unit: "per_sqft",
    use_cases: "commercial, living_room, bathroom",
    collection: "syncstone_platinum",
    brand: "Mozart",
    image_path: null,
    description: "Textured grey with a lightly embossed mosaic-micro pattern. Adds tactile depth while maintaining the clean look of concrete.",
  },
  {
    name: "Grani Sand",
    sku: "SS-GNS-PM",
    size: "600×1200",
    placement: "both",
    pattern: "stone",
    finish: "plume_matt",
    color: "beige",
    price: 200,
    price_unit: "per_sqft",
    use_cases: "outdoor, commercial, living_room",
    collection: "syncstone_platinum",
    brand: "Mozart",
    image_path: null,
    description: "Speckled granite-like surface in warm sand tones. Fullbody construction ensures consistent look even at cut edges.",
  },
  {
    name: "Brixstone",
    sku: "SS-BRX-PM",
    size: "600×1200",
    placement: "both",
    pattern: "stone",
    finish: "plume_matt",
    color: "beige",
    price: 205,
    price_unit: "per_sqft",
    use_cases: "outdoor, commercial, living_room",
    collection: "syncstone_platinum",
    brand: "Mozart",
    image_path: "/tiles/brixstone.jpg",
    description: "Multi-tonal stacked-brick stone pattern with an aged, quarried feel. Outstanding for exterior facades, accent walls and alfresco dining.",
  },
  {
    name: "Corten Stone",
    sku: "SS-CTS-PU",
    size: "600×1200",
    placement: "both",
    pattern: "abstract",
    finish: "punto",
    color: "brown",
    price: 250,
    price_unit: "per_sqft",
    use_cases: "living_room, lobby, outdoor",
    collection: "syncstone_platinum",
    brand: "Mozart",
    image_path: null,
    description: "Inspired by weathered Corten steel — a diagonal split of warm rusty-orange and cool grey. A bold, artistic statement surface.",
  },
  // ── Travertino Series ───────────────────────────────────────────────────────
  {
    name: "Travertino Natural",
    sku: "SS-TVN-PM",
    size: "600×1200",
    placement: "both",
    pattern: "stone",
    finish: "plume_matt",
    color: "beige",
    price: 220,
    price_unit: "per_sqft",
    use_cases: "living_room, lobby, commercial",
    collection: "syncstone_platinum",
    brand: "Mozart",
    image_path: "/tiles/travertino-natural.jpg",
    description: "Authentic travertine look in warm ivory-beige with delicate horizontal striations. Timeless elegance for premium residential and hotel projects.",
  },
  {
    name: "Travertino Gris",
    sku: "SS-TVG-PM",
    size: "600×1200",
    placement: "both",
    pattern: "stone",
    finish: "plume_matt",
    color: "grey",
    price: 220,
    price_unit: "per_sqft",
    use_cases: "living_room, lobby, commercial",
    collection: "syncstone_platinum",
    brand: "Mozart",
    image_path: "/tiles/travertino-gris.jpg",
    description: "Silver-grey travertine with fine horizontal grain. Brings an understated luxury to open-plan kitchens and corporate lobbies.",
  },
  {
    name: "Travertino Mint Dark",
    sku: "SS-TMD-PM",
    size: "600×1200",
    placement: "both",
    pattern: "stone",
    finish: "plume_matt",
    color: "beige",
    price: 225,
    price_unit: "per_sqft",
    use_cases: "living_room, commercial, lobby",
    collection: "syncstone_platinum",
    brand: "Mozart",
    image_path: null,
    description: "Rich warm-tan travertine with pronounced linear grain and dark accents. Creates depth and drama in large open spaces.",
  },
  {
    name: "Travertino Sand Light",
    sku: "SS-TSL-PM",
    size: "600×1200",
    placement: "both",
    pattern: "stone",
    finish: "plume_matt",
    color: "cream",
    price: 215,
    price_unit: "per_sqft",
    use_cases: "bedroom, living_room, lobby",
    collection: "syncstone_platinum",
    brand: "Mozart",
    image_path: null,
    description: "Pale cream travertine with fine wood-grain striations. Soft and serene — ideal for bedrooms, spa bathrooms and boutique hotel rooms.",
  },
  {
    name: "Travertino Sand Dark",
    sku: "SS-TSD-PM",
    size: "600×1200",
    placement: "both",
    pattern: "stone",
    finish: "plume_matt",
    color: "brown",
    price: 215,
    price_unit: "per_sqft",
    use_cases: "living_room, commercial, lobby",
    collection: "syncstone_platinum",
    brand: "Mozart",
    image_path: null,
    description: "Warm walnut-toned travertine with deep horizontal grain. A grounding, sophisticated choice for feature floors and wall panels.",
  },

  // ── Frame Collection ─────────────────────────────────────────────────────────
  {
    name: "Denim Cream Frame",
    sku: "FC-DCF-MT",
    size: "600×1200",
    placement: "wall",
    pattern: "frame",
    finish: "matt",
    color: "cream",
    price: 195,
    price_unit: "per_sqft",
    use_cases: "bathroom, bedroom, living_room",
    collection: "frame_collection",
    brand: "Mozart",
    image_path: "/tiles/frame-denim-cream.jpg",
    description: "Soft ivory-cream wall tile with an embossed frame punch texture inspired by European heritage panelling. Pairs beautifully with the Denim Cream Blossom floral decor.",
  },
  {
    name: "Denim Cream Frame Blossom",
    sku: "FC-DCB-MT",
    size: "600×1200",
    placement: "wall",
    pattern: "floral",
    finish: "matt",
    color: "cream",
    price: 215,
    price_unit: "per_sqft",
    use_cases: "bathroom, bedroom",
    collection: "frame_collection",
    brand: "Mozart",
    image_path: "/tiles/frame-denim-cream.jpg",
    description: "Chinoiserie-inspired cream tile adorned with hand-painted style botanical motifs in soft blues and gold. A statement accent for bathroom feature walls.",
  },
  {
    name: "Aqua Frame",
    sku: "FC-AQU-MT",
    size: "600×1200",
    placement: "wall",
    pattern: "frame",
    finish: "matt",
    color: "aqua",
    price: 190,
    price_unit: "per_sqft",
    use_cases: "living_room, dining_room, bedroom",
    collection: "frame_collection",
    brand: "Mozart",
    image_path: "/tiles/frame-aqua.jpg",
    description: "Tranquil mist-blue wall tile with a classic moulded frame texture. Brings a breath of fresh air to contemporary dining rooms and accent walls.",
  },
  {
    name: "Brick Frame",
    sku: "FC-BRK-MT",
    size: "600×1200",
    placement: "wall",
    pattern: "frame",
    finish: "matt",
    color: "salmon",
    price: 190,
    price_unit: "per_sqft",
    use_cases: "bathroom, bedroom",
    collection: "frame_collection",
    brand: "Mozart",
    image_path: "/tiles/frame-brick-french.jpg",
    description: "Terracotta-salmon wall tile with a deep embossed frame pattern. Adds warmth and character to bathrooms and feature walls.",
  },
  {
    name: "French Frame",
    sku: "FC-FRN-MT",
    size: "600×1200",
    placement: "wall",
    pattern: "frame",
    finish: "matt",
    color: "pink",
    price: 190,
    price_unit: "per_sqft",
    use_cases: "living_room, bathroom, bedroom",
    collection: "frame_collection",
    brand: "Mozart",
    image_path: "/tiles/frame-french.jpg",
    description: "Blush-pink wall tile with refined frame moulding for a romantic, Parisian-inspired interior. Effortlessly elegant in living spaces and en-suites.",
  },
  {
    name: "Carbon Frame",
    sku: "FC-CBN-MT",
    size: "600×1200",
    placement: "wall",
    pattern: "frame",
    finish: "matt",
    color: "dark_grey",
    price: 200,
    price_unit: "per_sqft",
    use_cases: "bedroom, living_room, commercial",
    collection: "frame_collection",
    brand: "Mozart",
    image_path: "/tiles/frame-carbon.jpg",
    description: "Moody charcoal-grey wall tile with an architectural frame emboss. Creates dramatic, masculine interiors in bedrooms and corporate spaces.",
  },
  {
    name: "Cement Frame",
    sku: "FC-CMT-MT",
    size: "600×1200",
    placement: "wall",
    pattern: "frame",
    finish: "matt",
    color: "grey",
    price: 185,
    price_unit: "per_sqft",
    use_cases: "living_room, commercial, lobby",
    collection: "frame_collection",
    brand: "Mozart",
    image_path: "/tiles/frame-cement.jpg",
    description: "Warm light-grey wall tile with a subtle frame texture. Versatile and modern — a natural choice for open-plan living rooms and fireplaces.",
  },
  {
    name: "Kota Frame",
    sku: "FC-KOT-MT",
    size: "600×1200",
    placement: "wall",
    pattern: "frame",
    finish: "matt",
    color: "sage",
    price: 195,
    price_unit: "per_sqft",
    use_cases: "bathroom, bedroom, living_room",
    collection: "frame_collection",
    brand: "Mozart",
    image_path: "/tiles/frame-kota.jpg",
    description: "Earthy sage-green wall tile with European panel detailing. Brings nature indoors — perfect for spa bathrooms and serene bedroom feature walls.",
  },
  {
    name: "Mushroom Frame",
    sku: "FC-MSH-MT",
    size: "600×1200",
    placement: "wall",
    pattern: "frame",
    finish: "matt",
    color: "taupe",
    price: 190,
    price_unit: "per_sqft",
    use_cases: "living_room, dining_room, commercial",
    collection: "frame_collection",
    brand: "Mozart",
    image_path: "/tiles/frame-mushroom.jpg",
    description: "Warm taupe-brown wall tile with a classic frame punch. Grounding and sophisticated — ideal for feature walls in living rooms and restaurants.",
  },
  {
    name: "Super White Frame",
    sku: "FC-SWF-MT",
    size: "600×1200",
    placement: "wall",
    pattern: "frame",
    finish: "matt",
    color: "white",
    price: 185,
    price_unit: "per_sqft",
    use_cases: "commercial, lobby, living_room",
    collection: "frame_collection",
    brand: "Mozart",
    image_path: "/tiles/frame-super-white.jpg",
    description: "Crisp pure-white wall tile with an embossed frame grid. Brings light, space and classical elegance to offices, lobbies and modern living areas.",
  },
  {
    name: "Windsor Frame",
    sku: "FC-WND-MT",
    size: "600×1200",
    placement: "wall",
    pattern: "frame",
    finish: "matt",
    color: "navy",
    price: 200,
    price_unit: "per_sqft",
    use_cases: "bedroom, living_room, commercial",
    collection: "frame_collection",
    brand: "Mozart",
    image_path: "/tiles/frame-windsor.jpg",
    description: "Deep slate-blue wall tile with a sculpted frame relief. Bold and contemporary — makes a strong statement in bedrooms and hospitality spaces.",
  },
  {
    name: "Leaf Frame",
    sku: "FC-LFR-MT",
    size: "600×1200",
    placement: "wall",
    pattern: "frame",
    finish: "matt",
    color: "green",
    price: 195,
    price_unit: "per_sqft",
    use_cases: "bathroom, living_room, bedroom",
    collection: "frame_collection",
    brand: "Mozart",
    image_path: "/tiles/frame-leaf.jpg",
    description: "Rich hunter-green wall tile with classic moulded frame pattern. Creates an immersive biophilic feel in bathrooms and feature walls.",
  },
  {
    name: "Canyon Dawn Frame",
    sku: "FC-CDF-MT",
    size: "600×1200",
    placement: "wall",
    pattern: "frame",
    finish: "matt",
    color: "cream",
    price: 195,
    price_unit: "per_sqft",
    use_cases: "commercial, lobby, living_room",
    collection: "frame_collection",
    brand: "Mozart",
    image_path: "/tiles/frame-canyon-dawn.jpg",
    description: "Off-white wall tile with fine frame emboss, perfect as a backdrop for the Canyon Dawn Frame Flora botanical decor accent. Ideal for boutique retail and hospitality.",
  },
  {
    name: "Canyon Dawn Frame Flora",
    sku: "FC-CFF-MT",
    size: "600×1200",
    placement: "wall",
    pattern: "floral",
    finish: "matt",
    color: "cream",
    price: 215,
    price_unit: "per_sqft",
    use_cases: "commercial, lobby, bedroom",
    collection: "frame_collection",
    brand: "Mozart",
    image_path: "/tiles/frame-canyon-dawn.jpg",
    description: "Elegant tropical leaf and frond artwork on a soft cream frame tile. A luxury accent piece for boutique hotels, dressing rooms and statement walls.",
  },

  // ── Wainscot Series ──────────────────────────────────────────────────────────
  {
    name: "French Wainscot",
    sku: "WS-FRN-MT",
    size: "600×1200",
    placement: "wall",
    pattern: "wainscot",
    finish: "matt",
    color: "pink",
    price: 175,
    price_unit: "per_sqft",
    use_cases: "living_room, bedroom, bathroom",
    collection: "wainscot_series",
    brand: "Mozart",
    image_path: "/tiles/wainscot-french.jpg",
    description: "Pale blush-pink wainscot tile with vertical beadboard groove pattern. Adds classic charm and soft femininity to living rooms and bedrooms.",
  },
  {
    name: "Brick Wainscot",
    sku: "WS-BRK-MT",
    size: "600×1200",
    placement: "wall",
    pattern: "wainscot",
    finish: "matt",
    color: "salmon",
    price: 175,
    price_unit: "per_sqft",
    use_cases: "bathroom, bedroom",
    collection: "wainscot_series",
    brand: "Mozart",
    image_path: "/tiles/wainscot-brick.jpg",
    description: "Warm terracotta-pink wainscot tile with slim vertical channels. Enlivens bathrooms with a playful, tactile panel effect.",
  },
  {
    name: "Mushroom Wainscot",
    sku: "WS-MSH-MT",
    size: "600×1200",
    placement: "wall",
    pattern: "wainscot",
    finish: "matt",
    color: "taupe",
    price: 175,
    price_unit: "per_sqft",
    use_cases: "bathroom, bedroom, living_room",
    collection: "wainscot_series",
    brand: "Mozart",
    image_path: "/tiles/wainscot-mushroom.jpg",
    description: "Understated taupe-brown wainscot with fine vertical beading. Pairs effortlessly with marble baths and wood accents for a warm, luxurious feel.",
  },
  {
    name: "Kota Wainscot",
    sku: "WS-KOT-MT",
    size: "600×1200",
    placement: "wall",
    pattern: "wainscot",
    finish: "matt",
    color: "sage",
    price: 175,
    price_unit: "per_sqft",
    use_cases: "dining_room, living_room, bedroom",
    collection: "wainscot_series",
    brand: "Mozart",
    image_path: "/tiles/wainscot-kota.jpg",
    description: "Muted sage-green wainscot tile evoking countryside calm. Stunning in dining rooms and studies with dark wood furniture.",
  },
  {
    name: "Leaf Wainscot",
    sku: "WS-LFW-MT",
    size: "600×1200",
    placement: "wall",
    pattern: "wainscot",
    finish: "matt",
    color: "green",
    price: 175,
    price_unit: "per_sqft",
    use_cases: "living_room, dining_room, bathroom",
    collection: "wainscot_series",
    brand: "Mozart",
    image_path: "/tiles/wainscot-leaf.jpg",
    description: "Deep teal-green wainscot with bold vertical grooves. Creates a rich, dramatic backdrop in living rooms and bathrooms.",
  },
  {
    name: "Super White Wainscot",
    sku: "WS-SWW-MT",
    size: "600×1200",
    placement: "wall",
    pattern: "wainscot",
    finish: "matt",
    color: "white",
    price: 165,
    price_unit: "per_sqft",
    use_cases: "living_room, bathroom, commercial",
    collection: "wainscot_series",
    brand: "Mozart",
    image_path: "/tiles/wainscot-super-white.jpg",
    description: "Classic bright-white beadboard wainscot. Timeless and versatile — brings a light, airy heritage feel to any interior from cottages to contemporary homes.",
  },
  {
    name: "Cement Wainscot",
    sku: "WS-CMW-MT",
    size: "600×1200",
    placement: "wall",
    pattern: "wainscot",
    finish: "matt",
    color: "grey",
    price: 170,
    price_unit: "per_sqft",
    use_cases: "living_room, commercial, bedroom",
    collection: "wainscot_series",
    brand: "Mozart",
    image_path: "/tiles/wainscot-cement.jpg",
    description: "Cool mid-grey wainscot tile with slim vertical panel grooves. Suits contemporary and Scandi interiors — pairs beautifully with concrete floors and linen sofas.",
  },
  {
    name: "Carbon Wainscot",
    sku: "WS-CBW-MT",
    size: "600×1200",
    placement: "wall",
    pattern: "wainscot",
    finish: "matt",
    color: "dark_grey",
    price: 175,
    price_unit: "per_sqft",
    use_cases: "bedroom, commercial, bathroom",
    collection: "wainscot_series",
    brand: "Mozart",
    image_path: "/tiles/wainscot-carbon.jpg",
    description: "Dark slate-grey wainscot with a refined vertical groove detail. Creates a moody, luxurious atmosphere in master bedrooms and boutique hotel rooms.",
  },
  {
    name: "Aqua Wainscot",
    sku: "WS-AQW-MT",
    size: "600×1200",
    placement: "wall",
    pattern: "wainscot",
    finish: "matt",
    color: "aqua",
    price: 170,
    price_unit: "per_sqft",
    use_cases: "bathroom, bedroom, living_room",
    collection: "wainscot_series",
    brand: "Mozart",
    image_path: "/tiles/wainscot-aqua.jpg",
    description: "Fresh seafoam-green wainscot tile with vertical bead detailing. Brings a spa-like freshness to bathrooms and powder rooms.",
  },
  {
    name: "Windsor Wainscot",
    sku: "WS-WNW-MT",
    size: "600×1200",
    placement: "wall",
    pattern: "wainscot",
    finish: "matt",
    color: "navy",
    price: 175,
    price_unit: "per_sqft",
    use_cases: "living_room, bedroom, commercial",
    collection: "wainscot_series",
    brand: "Mozart",
    image_path: "/tiles/wainscot-windsor.jpg",
    description: "Classic denim-blue wainscot with tall vertical panelling. Combines the heritage of English country homes with a modern, sophisticated colour palette.",
  },
];

// ── Insert tiles ──────────────────────────────────────────────────────────────
// Clear existing tiles first for a clean seed
db.exec("DELETE FROM tiles");

const stmt = db.prepare(`
  INSERT INTO tiles
    (name, sku, size, placement, pattern, finish, color, price, price_unit,
     use_cases, collection, brand, image_path, description)
  VALUES
    (@name, @sku, @size, @placement, @pattern, @finish, @color, @price, @price_unit,
     @use_cases, @collection, @brand, @image_path, @description)
`);

const insertAll = db.transaction(() => {
  for (const tile of tiles) stmt.run(tile);
});

insertAll();
console.log(`✓ Seeded ${tiles.length} tiles.`);

// Export to JSON for Vercel (no SQLite native module needed at runtime)
import { writeFileSync } from "fs";
const allTiles = db.prepare("SELECT * FROM tiles").all();
const allFilters = db.prepare("SELECT * FROM filter_options").all();
writeFileSync(join(__dirname, "../data/tiles.json"), JSON.stringify(allTiles, null, 2));
writeFileSync(join(__dirname, "../data/filter-options.json"), JSON.stringify(allFilters, null, 2));
console.log(`✓ Exported tiles.json (${allTiles.length}) and filter-options.json (${allFilters.length}).`);

db.close();
